alias jirai="jira issue"
alias jirails="jira issue ls"
alias jiraic="jira issue comment"
alias jiraitr="jira issue trans"
alias jiraimy="jira issue ls -a watsy0007"
alias jiras="jira sprint"
alias jirap="jira project"
